SIM ?= icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(CURDIR)/../src/v2_engine.v
TOPLEVEL = protocol_engine_v2
COCOTB_TEST_MODULES = test_v2_engine
SIM_BUILD = sim_build/v2
COCOTB_RESULTS_FILE = results_v2.xml
export PYTHONPATH := $(CURDIR)/../host:$(PYTHONPATH)
include $(shell cocotb-config --makefiles)/Makefile.sim
