SIM ?= icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(CURDIR)/../src/v2_capture.v
TOPLEVEL = protocol_capture_v2
COCOTB_TEST_MODULES = test_v2_capture
SIM_BUILD = sim_build/v2capture
COCOTB_RESULTS_FILE = results_v2_capture.xml
# Small counter exercises exhaustion; production defaults to 32 bits.
COMPILE_ARGS += -Pprotocol_capture_v2.TIMESTAMP_WIDTH=8
export PYTHONPATH := $(CURDIR)/../host:$(PYTHONPATH)
include $(shell cocotb-config --makefiles)/Makefile.sim
