name: fpga

on:
  push:
    # Comment out (or remove) the following line to run the FPGA workflow on every push:
    branches: none
  workflow_dispatch:

jobs:
  fpga:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          submodules: recursive

      - name: FPGA bitstream for TT ASIC Sim (ICE40UP5K)
        uses: TinyTapeout/tt-gds-action/fpga/ice40up5k@3412659307918422f3f0727917cf9b499aaca588
